DjangoWebProject4/DjangoWebProject4/urls.py
"""
Definition of urls for DjangoWebProject4.
"""

from datetime import datetime
from django.urls import path, re_path
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.conf import settings
from django.conf.urls import include
admin.autodiscover()


urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.blog, name='blog'),
    re_path(r'^(?P<parametr>\d+)/$', views.article, name='article'),
    path('links/', views.links, name='links'),
    path('feedback/', views.feedback, name='feedback'),
    path('videopost/', views.videopost, name='videopost'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('registration/', views.registration, name='registration'),
    path('newpost/', views.newpost, name='newpost'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

DjangoWebProject4/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from .models import Comment, Article

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Логин'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class FeedbackForm(forms.Form):
    name = forms.CharField(
        label="Ваше имя",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        min_length=2,
        max_length=100,
    )
    gender = forms.ChoiceField(
        label="Ваш пол",
        choices=(("m", "Мужской"), ("f", "Женский")),
        widget=forms.RadioSelect,
    )
    notice = forms.BooleanField(label="Получать новости на e-mail", required=False)
    email = forms.EmailField(
        label="Ваш e-mail",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        min_length=7,
    )
    message = forms.CharField(
        label="Ваши предложения по улучшению сайта",
        widget=forms.Textarea(attrs={"rows": 8, "cols": 20, "class": "form-control"}),
        required=False,
    )

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = (
            "title",
            "description",
            "content",
            "image",
        )
        labels = {
            "title": "Заголовок",
            "description": "Краткое содержание",
            "content": "Полное содержание",
            "image": "Картинка",
        }
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"class": "form-control"})}

DjangoWebProject4/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Используйте место для дополнительной информации.</p>

{% endblock %}

DjangoWebProject4/app/templates/app/article.html
{% extends "app/layout.html" %}

{% block content %}

<p class="vertical-margins"><a class="btn btn-default" href="{% url 'blog' %}">&laquo; Назад</a></p>

<h2>{{ post.title }}</h2>

{% if post.image and post.image.url != "/media/temp.jpg" %}
<div class="row vertical-margins">
    <div class="col-md-6 col-md-offset-3">
        <img src="{{ post.image.url }}" alt="Картинка" class="img-responsive img-rounded" />
    </div>
</div>
{% endif %}

<div class="article-content"><p>{{ post.content|linebreaksbr }}</p></div>

{% if user.is_authenticated %}

<h3>Добавить комментарий</h3>

<form method="post">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Отправить комментарий</button>
    </div>
</form>

{% else %}

<h3>Для добавления своего комментария, пожалуйста, авторизуйтесь</h3>

{% endif %}

{% for comment in comments %}

<hr />
<h7> {{ comment.date }} </h7>
<h5 class="comment-author colorauthor"> {{ comment.author }} </h5>
<p> {{ comment.text|linebreaksbr }} </p>

{% endfor %}

{% endblock %}

DjangoWebProject4/app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>

{% for post in posts %}

<hr />

<div class="row">
    <div class="col-md-2">
        {% if post.image and post.image.url != "/media/temp.jpg" %}
        <img src="{{ post.image.url }}" alt="Картинка" class="img-responsive img-rounded" style="margin-top: 20px" />
        {% endif %}
    </div>
    <div class="col-md-6">
        <h2>{{ post.title }}</h2>
        <h4>{{ post.posted }}</h4>
        <p>{{ post.description }}</p>
        <p><a href="{% url 'article' parametr=post.id %}">Читать далее</a></p>
    </div>
</div>

{% endfor %}

{% endblock %}

DjangoWebProject4/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Адрес<br />
    Улица<br />
    <abbr title="Телефон">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Саппорт:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Маркетинг:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

DjangoWebProject4/app/templates/app/feedback.html
{% extends "app/layout.html" %}

{% block content %}

{% if data != None %}

<h2>Спасибо за отзыв!</h2>
<h3>Вы отправили:</h3>

<ul class="list-unstyled">
    <li>Имя: {{ data.name }}</li>
    <li>Пол: {{ data.gender }}</li>
    <li>Согласие на рассылку: {{ data.notice }}</li>
    <li>e-mail: {{ data.email }}</li>
    <li>Отзыв: {{ data.message }}</li>
</ul>

{% else %}

<h2>Заполните анкету</h2>

<form method="post">
    {% csrf_token %}

    <table class="table-form">
        <tr>
            <td><label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label></td>
            <td>{{ form.name }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}</label></td>
            <td>{{ form.gender }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.notice.id_for_label }}">{{ form.notice.label }}</label></td>
            <td>{{ form.notice }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label></td>
            <td>{{ form.email }}</td>
        </tr>
        <tr>
            <td><label for="{{ form.message.id_for_label }}">{{ form.message.label }}</label></td>
            <td>{{ form.message }}</td>
        </tr>
    </table>

    <input class="activebutton changecolor" type="submit" value="Отправить">
</form>
<script>
    $(".changecolor").mouseover(function () {
        $(this).css("background-color", "red")
    }).mouseout(function () {
        $(this).css("background-color", "white")
    });
    $("#id_message").mouseover(function () {
        $(this).css("background-color", "red")
    }).mouseout(function () {
        $(this).css("background-color", "white")
    });
    $("#id_name").mouseover(function () {
        $(this).css("background-color", "red")
    }).mouseout(function () {
        $(this).css("background-color", "white")
    });
    $("#id_email").mouseover(function () {
        $(this).css("background-color", "red")
    }).mouseout(function () {
        $(this).css("background-color", "white")
    });
</script>



{% endif %}

{% endblock %}

DjangoWebProject4/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}


{% load static %}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="10000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'app/content/11.svg'%} " width="315px" height="200" alt="Первый слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Джанго
                    <a class="btn btn-default" href="https://www.djangoproject.com/">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="{% static 'app/content/12.svg'%}" width="400px" height="200px" alt="Второй слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Python
                    <a class="btn btn-default" href="https://www.python.org/">
                        Перейти
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/13.svg'%} " width="400px" height="200px" alt="Третий слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    JS
                    <a class="btn btn-default" href="https://learn.javascript.ru/">
                        Выучить
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Назад</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Вперёд</span>
    </a>
</div>

<div class="jumbotron">
    <h1>Django</h1>
    <p class="lead">Джанго бесплатный крутой фреймворк.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Узнать больше &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Начинаем</h2>
        <p>
            Джанго это просто пушечка. Обожаю джанго, который освобожденный.
        </p>
        <p><a class="btn btn-default" href="https://djangobook.com/django-tutorials/">Узнай больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Больше библиотек</h2>
        <p>Штуки для питона.</p>
        <p><a class="btn btn-default" href="https://pypi.org/">Узнай больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>Можешь бесплатно попробовать азур.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Узнай больше &raquo;</a></p>
    </div>
</div>

{% endblock %}

DjangoWebProject4/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Моё приложение на джанго</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    

</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/logo.png' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                    {% endif %}
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    <li><a href="{% url 'feedback' %}">Обратная связь</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Моё приложение на освобожденном</p>
        </footer>
    </div>

    
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

DjangoWebProject4/app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}

{% load static %}

<h2>Полезные ресурсы</h2>



<h3>Связанные по тематике сайты</h3>

<br />

<ul class="row list-unstyled list">
    <li class="col-md-4">
        <a href="https://www.python.org/">
            <img src="{% static 'app/content/python.png'%} " width="100" height="111" alt="python" />
        </a>
    </li>
    <li class="col-md-4">
        <a href="https://djangobook.com/">
            <img src="{% static 'app/content/django.png'%} " width="100" height="111" alt="django" />
        </a>
    </li>
    <li class="col-md-4">
        <a href="https://learn.javascript.ru/">
            <img src="{% static 'app/content/js.png'%} " width="100" height="111" alt="js" />
        </a>
    </li>
</ul>

{% endblock %}

DjangoWebProject4/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Вход</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используй акк для входа</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Пользователь</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Вход" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Введите верный логин и пароль</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

DjangoWebProject4/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выход</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Вход</a></li>
</ul>

{% endif %}

DjangoWebProject4/app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Добавить статью</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row newpost">
        <table class="col-md-8">
            {{ articleForm.as_table }}
        </table>
    </div>
    <button type="submit" class="save btn btn-default vertical-margins">Сохранить статью</button>
</form>

{% endblock %}

DjangoWebProject4/app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Регистрация пользователя</h2>

<form method="post">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Регистрация</button>
    </div>
</form>

{% endblock %}

DjangoWebProject4/app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Видео</h2>

<div>
    <h3>Видео 1</h3>
    <video src="/media/1.mp4" controls="controls" width="400" height="300" poster="/media/321.png"></video>
</div>

<hr />

<div>
    <h3>Видео 2</h3>
    <video src="/media/2.mp4" controls="controls" width="400" height="300" poster="/media/123.jpg"></video>
</div>

{% endblock %}